### ISSUE TITLE
 Project Plan (Grant Chart)

### ISSUE THREAD

**Issue by DanthakaSri** [chrishanpeiris/cdu-mas#2]
Create Project Plan using grant chart

**Comment by chrishanpeiris** [comment]
![ghantt-chart-cdu-mas](https://user-images.githubusercontent.com/12605681/37705622-29749b3e-2d44-11e8-9381-51f178e0cb0e.jpg)
Ghantt chart added. Please review.

**Comment by DanthakaSri** [comment]
@chrishanpeiris  Perfect, I'm agree with this project plan.

**Comment by haihau** [comment]
Good job!

**Comment by chrishanpeiris** [comment]
[Gantt-chart-cdu-mas.zip](https://github.com/chrishanpeiris/cdu-mas/files/1832891/Gantt-chart-cdu-mas.zip)

Adding the actual source file of Gantt chart.
