### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by DanthakaSri** [chrishanpeiris/cdu-mas#4]
Define the Scope of the Project

**Comment by haihau** [comment]
[Scope.docx](https://github.com/chrishanpeiris/cdu-mas/files/1832153/Scope.docx)

**Comment by DanthakaSri** [comment]
[Scope.docx](https://github.com/chrishanpeiris/cdu-mas/files/1832950/Scope.docx)
I have edited and upload the document. All are agreed to project scope
