### ISSUE TITLE
Feasibility Studies

### ISSUE THREAD

**Issue by DanthakaSri** [chrishanpeiris/cdu-mas#5]
Feasibility study about the App and please include in Software Requirement Specification document

**Comment by DanthakaSri** [comment]
[task 2_week3.docx](https://github.com/chrishanpeiris/cdu-mas/files/1833027/task.2_week3.docx)
Hi All, here I have attached the feasibility study and requirment
@haihau

**Comment by haihau** [comment]
Nice done.
