### ISSUE TITLE
Requirements analysis

### ISSUE THREAD

**Issue by DanthakaSri** [chrishanpeiris/cdu-mas#6]
Please do the requirements elicitation and analysis about the App and include in System Requirement Specification Document

**Comment by haihau** [comment]
[Requirements.docx](https://github.com/chrishanpeiris/cdu-mas/files/1832157/Requirements.docx)

**Comment by DanthakaSri** [comment]
I think we should add the below mentioned requirement to the document

RQ8 – Generate student attendance summary | Generate student attendance summary for every class

**Comment by haihau** [comment]
Requirement document is updated.

**Comment by DanthakaSri** [comment]
Great this is good.

**Comment by chrishanpeiris** [comment]
Agreed. great job.
