### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by haihau** [chrishanpeiris/cdu-mas#7]
![prototype](https://user-images.githubusercontent.com/37144635/37874155-a2bbe1c4-3068-11e8-8e8c-9b0e04b77baa.png)

**Comment by DanthakaSri** [comment]
@haihau  In lecturer user interface, I think we should give an option to select the course that lecturer wants to mark the attendance.

**Comment by DanthakaSri** [comment]
@haihau @chrishanpeiris @ujjwal46  ,Hi All here I have attached the prototype sketeches
Please go through it and comment

![drawing_symbols](https://user-images.githubusercontent.com/8748446/38030045-af85a4e2-32d6-11e8-9d44-5f60eaecd2a8.png)
![lecturer](https://user-images.githubusercontent.com/8748446/38030046-afc1ea06-32d6-11e8-937d-46e0db82e30d.png)
![login](https://user-images.githubusercontent.com/8748446/38030047-afff404a-32d6-11e8-94e9-1ec11b049191.png)
![student](https://user-images.githubusercontent.com/8748446/38030048-b04d16bc-32d6-11e8-8eec-4167be63ad97.png)

**Comment by chrishanpeiris** [comment]
Please try to use above sketches in marvel app and make it interactive. Just to learn marvel app as lecture suggested.

**Comment by chrishanpeiris** [comment]
Hi all, please find the attached sketches of mine. We will discuss tomorrow and design a final common prototype. 
[Sketches.pdf](https://github.com/chrishanpeiris/cdu-mas/files/1856229/Sketches.pdf)

**Comment by chrishanpeiris** [comment]
Here is the marvelapp interaction for the sketches - https://marvelapp.com/43cfae8/screen/40398067

**Comment by DanthakaSri** [comment]
@chrishanpeiris  please add the basic prototype that we agreed with client and close the issue
